[tool.poetry]
name = "dash_charts"
version = "0.0.4"
description = "Python package for OOP of Plotly/Dash apps and custom templates"
authors = ["Kyle King <https://github.com/KyleKing>"]
repository = "https://github.com/kyleking/dash_charts"

[tool.poetry.dependencies]
python = "^3.7, !=3.8"
bottleneck = "*"
cerberus = "*"
dash = "*"
dash-bootstrap-components = "*"
dominate = "*"
icecream = "*"
markdown = "*"
pandas = "*"
scipy = "*"

[tool.poetry.dev-dependencies]
dash = {extras = ["testing"], version = "*, ^1.11"}
dash_dev = {git = "https://github.com/KyleKing/dash_dev.git"}
jsonpickle = "*"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
