[build-system]
requires = [ "poetry>=1.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dash_charts"
version = "0.0.5"
description = "Python package for OOP of Plotly/Dash apps and custom templates"
authors = [ "Kyle King <https://github.com/KyleKing>",]
repository = "https://github.com/kyleking/dash_charts"

[tool.poetry.dependencies]
python = "^3.7, !=3.8"
bottleneck = "*"
cerberus = "*"
dash = "*"
dash-bootstrap-components = "*"
dataset = "*"
dominate = "*"
icecream = "*"
markdown = "*"
pandas = "*"
psutil = "*"
scipy = "*"

[tool.poetry.dev-dependencies]
jsonpickle = "*"

[tool.poetry.dev-dependencies.dash]
extras = [ "testing",]
version = "*, ^1.11"

[tool.poetry.dev-dependencies.dash_dev]
git = "https://github.com/KyleKing/dash_dev.git"
