[tool.isort]
line_length = 120
length_sort = false
default_section = "THIRDPARTY"

[tool.poetry]
name = "dash_charts"
version = "0.0.4"
description = "Python package for OOP of Plotly/Dash apps and custom templates"
authors = ["Kyle King <KyleKing@users.noreply.github.com>", ]
repository = "https://github.com/kyleking/dash_charts"

[tool.poetry.dependencies]
python = "^3.7, !=3.8"
bottleneck = "*"
cerberus = "^1.3.2"
dash = "*, ^1.9"
icecream = "*"
pandas = "*"
pystache = "^0.5.4"
scipy = "*"

[tool.poetry.dev-dependencies]
add-trailing-comma = "^2.0.1"
autopep8 = "*"
beautifulsoup4 = "*"
cohesion = "*"
darglint = "*"
dash = {extras = ["testing"], version = "*, ^1.9"}
dash_daq = "*"
dash-bootstrap-components = "*"
diff-cover = "*"
dlint = "*"
doit = "*"
flake8 = "*"
flake8-2020 = "*"
flake8-aaa = "*"
flake8-assertive = "*"
flake8-bandit = "*"
flake8-blind-except = "*"
flake8-breakpoint = "*"
flake8-broken-line = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-cognitive-complexity = "*"
flake8-commas = "*"
flake8-comprehensions = "*"
flake8-debugger = "*"
flake8-deprecated = "*"
flake8-docstrings = "*"
flake8-eradicate = "*"
flake8-fixme = "*"
flake8-functions = "*"
flake8-isort = "*"
flake8-logging-format = "*"
flake8-markdown = "*"
flake8-mock = "*"
flake8-mutable = "*"
flake8-pep3101 = "*"
flake8-plone-hasattr = "*"
flake8-print = "*"
flake8-printf-formatting = "*"
flake8-pytest-style = "*"
flake8-quotes = "*"
flake8-return = "*"
flake8-spellcheck = "*"
flake8-sql = "*"
flake8-string-format = "*"
flake8-tuple = "*"
flake8-variables-names = "*"
gitchangelog = "*"
iniparse = "*"
isort = "*"
pandas-vet = "*"
pdoc3 = "^0.7.5"
pep8-naming = "*"
proselint = "*"
pur = "*"
pytest = "*"
pytest-cov = "*"
pytest-html = "*"
pyupgrade = "*"
radon = "*"
toml = "*"
tqdm = "*"
transitions = "*"
vulture = "*"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
