[tool.isort]
line_length = 120
length_sort = false
default_section = "THIRDPARTY"

[tool.poetry]
name = "dash_charts"
version = "0.0.4"
description = "Helpful functions and classes for building Plotly Dash apps/dashboards"
authors = ["Kyle King <KyleKing@users.noreply.github.com>", ]
repository = "https://github.com/kyleking/dash_charts"

[tool.poetry.dependencies]
python = "^3.7"
bottleneck = "^1.2"
dash = "^1.9"
icecream = "^2.0"
pandas = "^1.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.4"
cohesion = "^1.0.0"
darglint = "^1.1.2"
dash-bootstrap-components = "^0.8.3"
diff-cover = "^2.5.2"
dlint = "^0.10.1"
doit = "^0.32"
flake8 = "^3.7"
flake8-2020 = "^1.5.0"
flake8-aaa = "^0.7.1"
flake8-assertive = "^1.2.1"
flake8-bandit = "^2.1.2"
flake8-blind-except = "^0.1"
flake8-breakpoint = "^1.1.0"
flake8-broken-line = "^0.1.1"
flake8-bugbear = "^20.1"
flake8-builtins = "^1.4"
flake8-cognitive-complexity = "^0.0.2"
flake8-commas = "^2.0"
flake8-comprehensions = "^3.2.2"
flake8-debugger = "^3.2.1"
flake8-deprecated = "^1.3"
flake8-docstrings = "^1.5.0"
flake8-eradicate = "^0.2.4"
flake8-fixme = "^1.1.1"
flake8-functions = "^0.0.2"
flake8-isort = "^2.7"
flake8-logging-format = "^0.6"
flake8-markdown = "^0.2.0"
flake8-mock = "^0.3"
flake8-mutable = "^1.2.0"
flake8-pep3101 = "^1.3.0"
flake8-plone-hasattr = "^0.2"
flake8-print = "^3.1"
flake8-printf-formatting = "^1.1.0"
flake8-pytest-style = "^0.1.3"
flake8-quotes = "^2.0"
flake8-return = "^1.1.1"
flake8-spellcheck = "^0.12.1"
flake8-sql = "^0.4.0"
flake8-string-format = "^0.2.3"
flake8-tuple = "^0.4"
flake8-variables-names = "^0.0.3"
gitchangelog = "^3.0"
iniparse = "^0.5"
isort = "^4.3"
pandas-vet = "^0.2.1"
# pdoc3 = "^0.7.5"  # TODO: uncomment once 0.7.5 is available with fix for data members
pdoc3 = {git= "https://github.com/pdoc3/pdoc.git"}
pep8-naming = "^0.9"
plotly_express = "^0.4"
proselint = "^0.10.2"
pur = "^5.2"
pytest = "^5.0"
pytest-cov = "^2.7"
pytest-html = "^2.0"
pyupgrade = "^1.26.2"
radon = "^4.0"
toml = "^0.10"
tqdm = "^4.32"
vulture = "^1.3"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
