[build-system]
requires = [ "poetry-core>=1.0",]
build-backend = "poetry.core.masonry.api"

[tool.isort]
balanced_wrapping = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
length_sort = false
line_length = 120

[tool.poetry]
name = "dash_charts"
version = "0.0.5"
description = "Python package for OOP of Plotly/Dash apps and custom templates"
license = "MIT"
authors = [ "Kyle King <https://github.com/KyleKing>",]
maintainers = []
readme = "README.md"
repository = "https://github.com/kyleking/dash_charts"
documentation = "https://kyleking.me/dash_charts/"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kyleking/dash_charts/issues"

[tool.poetry.dependencies]
python = "^3.7"
cerberus = "*"
dash = "*"
dash-bootstrap-components = "*"
dataset = "*"
dominate = "*"
implements = "*"
markdown = "*"
Palettable = "*"
pandas = "*"
psutil = "*"
scipy = "*"
snoop = "*"

[tool.poetry.dev-dependencies]
astor = "*"
jsonpickle = "*"
matplotlib = "~3.1"

[tool.poetry.dev-dependencies.dash]
extras = [ "testing",]
version = "^1.16"

[tool.poetry.dev-dependencies.dash_dev]
git = "https://github.com/KyleKing/dash_dev.git"
