[tool.isort]
line_length = 120
length_sort = false
default_section = "THIRDPARTY"

[tool.poetry]
name = "dash-helloworld"
version = "0.0.1"
description = "Experiments with plotly Dash: https://dash.plot.ly/"
authors = ["Kyle King <KyleKing@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
dash = {git = "https://github.com/plotly/dash"}
dash-core-components = "^0.48.0"
dash-daq = "^0.1.4"
dash-html-components = "^0.16.0"
dash-table = "^3.7"
pandas = "^0.24.2"

[tool.poetry.dev-dependencies]
doit = "^0.31.1"
flake8 = "^3.7"
flake8-blind-except = "^0.1.1"
flake8-bugbear = "^19.3"
flake8-builtins = "^1.4"
flake8-commas = "^2.0"
flake8-deprecated = "^1.3"
flake8-isort = "^2.7"
flake8-logging-format = "^0.6.0"
flake8-mock = "^0.3.0"
flake8-print = "^3.1"
flake8-quotes = "^2.0"
flake8-tuple = "^0.3.1"
isort = "^4.3"
pep8-naming = "^0.8.2"
pytest = "^4.6"
pytest-cov = "^2.7"
radon = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
