[tool.isort]
line_length = 120
length_sort = false
default_section = "THIRDPARTY"

[tool.poetry]
name = "dash_charts"
version = "0.0.2"
description = "Helpful functions for Plotly Dash apps"
authors = ["Kyle King <KyleKing@users.noreply.github.com>"]
repository = "https://github.com/kyleking/dash_charts"

[tool.poetry.dependencies]
python = "^3.7"
bottleneck = "^1.2"
dash = {git = "https://github.com/plotly/dash.git"}
dash-core-components = {git = "https://github.com/plotly/dash-core-components.git"}
dash-daq = {git = "https://github.com/plotly/dash-daq.git"}
dash-html-components = {git = "https://github.com/plotly/dash-html-components.git"}
dash-table = {git = "https://github.com/plotly/dash-table.git"}
icecream = "^1.5"
pandas = "^0.24.2"
plotly = "^3.10"
plotly_express = "^0.3.1"
statsmodels = {path = "/Users/kyleking/Downloads/statsmodels-0.10.0rc2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl"}

[tool.poetry.dev-dependencies]
doit = "^0.31.1"
flake8 = "^3.7"
flake8-blind-except = "^0.1.1"
flake8-bugbear = "^19.3"
flake8-builtins = "^1.4"
flake8-commas = "^2.0"
flake8-deprecated = "^1.3"
flake8-isort = "^2.7"
flake8-logging-format = "^0.6.0"
flake8-mock = "^0.3.0"
flake8-print = "^3.1"
flake8-quotes = "^2.0"
flake8-tuple = "^0.3.1"
isort = "^4.3"
pdoc3 = "^0.6.2"
pep8-naming = "^0.8.2"
pytest = "^4.6"
pytest-cov = "^2.7"
radon = "^3.0"
toml = "^0.10.0"
tqdm = "^4.32"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
