[tool.flake8]
# Pending support in flake8: https://gitlab.com/pycqa/flake8/merge_requests/245
max-line-length = 120
ignore = "E265,E266,E262,E121,E123,E126,E24,E704,N802,N803,N806,N815,N816"

[tool.isort]
line_length = 120
length_sort = false
default_section = "THIRDPARTY"

[tool.poetry]
name = "dash-helloworld"
version = "0.0.1"
description = "Experiments with plotly Dash: https://dash.plot.ly/"
authors = ["Kyle King <KyleKing@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
dash = "^0.43.0"
dash-core-components = "^0.48.0"
dash-daq = "^0.1.5"
dash-html-components = "^0.16.0"
dash-table = "^3.7"
pandas = "^0.24.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-blind-except = "^0.1.1"
flake8-bugbear = "^19.3"
flake8-builtins = "^1.4"
flake8-commas = "^2.0"
flake8-deprecated = "^1.3"
flake8-isort = "^2.7"
flake8-logging-format = "^0.6.0"
flake8-mock = "^0.3.0"
flake8-print = "^3.1"
flake8-quotes = "^2.0"
isort = "^4.3"
pep8-naming = "^0.8.2"
pyinstaller = "^3.4"
pytest = "^4.4"
pytest-cov = "^2.6"
radon = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
