[build-system]
requires = [ "poetry>=1.0",]
build-backend = "poetry.core.masonry.api"

[tool.isort]
combine_as_imports = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
# import_heading_firstparty = "First party"
# import_heading_localfolder = "Local Folder"
# import_heading_thirdparty = "Third party"
length_sort = false
line_length = 120
multi_line_output = 0

# ["setup.cfg".flake8]
# annoy = true
# assertive-snakecase = true
# cohesion-below = 20.0
# docstring-convention = "all"
# ignore = "D203,D213,D214,D406,D407,G004,PD005,PD011,S322,SC100,SC200,W503"
# max-cognitive-complexity = 5
# max-function-length = 55
# max-line-length = 120
# max-parameters-amount = 6
# per-file-ignores = "test_*.py:S101"
# select = "A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z"
# # ignore = "D107,D202,D203,D401"
# # max-line-length = 120

[tool.poetry]
name = "dash_charts"
version = "0.0.5"
description = "Python package for OOP of Plotly/Dash apps and custom templates"
license = "MIT"
authors = [ "Kyle King <https://github.com/KyleKing>",]
maintainers = []
readme = "README.md"
repository = "https://github.com/kyleking/dash_charts"
documentation = "https://kyleking.me/dash_charts/"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kyleking/dash_charts/issues"

[tool.poetry.dependencies]
python = "^3.7"
bottleneck = "*"
cerberus = "*"
dash = "*"
dash-bootstrap-components = "*"
dataset = "*"
dominate = "*"
markdown = "*"
Palettable = "*"
pandas = "*"
psutil = "*"
scipy = "*"

[tool.poetry.dev-dependencies]
jsonpickle = "*"
matplotlib = "~3.1"  # See: https://github.com/plotly/plotly.py/issues/1568#issuecomment-653764327

[tool.poetry.dev-dependencies.dash]
extras = [ "testing",]
version = "^1.14"

[tool.poetry.dev-dependencies.dash_dev]
git = "https://github.com/KyleKing/dash_dev.git"
